# WHAT: Initialise the project — create folder structure, extract raw PDFs,
#       define global constants, and register the shared ggplot2 theme used
#       by every downstream figure script.
# WHY:  Single source of truth for paths, seeds, and aesthetics so all scripts
#       stay consistent without repeating boilerplate.
# INPUTS:  legiscan/Legiscan.zip
# OUTPUTS: data/, results/, figures/, validation/, analysis_explanations/,
#          Powerpoints/ folders; extracted PDFs in data/raw_pdfs/;
#          constants and theme written to global_constants.R (sourced by others)
# ESTIMATED RUNTIME: < 30 seconds

# ── Libraries ────────────────────────────────────────────────────────────────
library(tidyverse)

# ── Global constants ─────────────────────────────────────────────────────────
SEED     <- 42
MAX_BILLS <- 50          # total PDFs in the zip; set lower to test on a subset

ZIP_PATH  <- "legiscan/Legiscan.zip"
RAW_DIR   <- "data/raw_pdfs"

# ── Create folder structure ──────────────────────────────────────────────────
dirs <- c(
  "data",
  "data/raw_pdfs",
  "results",
  "figures",
  "validation",
  "analysis_explanations",
  "Powerpoints"
)

for (d in dirs) {
  if (!dir.exists(d)) {
    dir.create(d, recursive = TRUE)
    cat("Created:", d, "\n")
  } else {
    cat("Already exists:", d, "\n")
  }
}

# ── Extract zip ──────────────────────────────────────────────────────────────
cat("\nExtracting", ZIP_PATH, "...\n")

unzip(
  zipfile = ZIP_PATH,
  exdir   = RAW_DIR,
  overwrite = FALSE   # don't clobber if re-run
)

pdf_files <- list.files(RAW_DIR, pattern = "\\.pdf$", recursive = TRUE,
                        full.names = TRUE)
cat("PDFs found after extraction:", length(pdf_files), "\n")

if (length(pdf_files) == 0) stop("No PDFs found — check ZIP_PATH.")

# ── Shared ggplot2 theme ─────────────────────────────────────────────────────
# Clean, B&W-compatible theme to match the PowerPoint aesthetic.
# Applied to every figure in the project.

ACCENT_COLOR  <- "#2C4770"   # single navy accent used across all charts
GRAY_DARK     <- "#1A1A1A"   # near-black for titles / axis text
GRAY_MID      <- "#555555"   # secondary labels
GRAY_LIGHT    <- "#E8E8E8"   # faint reference lines

bills_theme <- theme_minimal(base_size = 13) +
  theme(
    # Background
    plot.background  = element_rect(fill = "white", color = NA),
    panel.background = element_rect(fill = "white", color = NA),

    # Grid — keep only faint horizontal lines
    panel.grid.major.y = element_line(color = GRAY_LIGHT, linewidth = 0.4),
    panel.grid.major.x = element_blank(),
    panel.grid.minor   = element_blank(),

    # Axes
    axis.text  = element_text(color = GRAY_MID,  size = 10),
    axis.title = element_text(color = GRAY_DARK, size = 11, face = "bold"),
    axis.ticks = element_blank(),
    axis.line  = element_blank(),

    # Titles
    plot.title    = element_text(color = GRAY_DARK, size = 14, face = "bold",
                                 margin = margin(b = 6)),
    plot.subtitle = element_text(color = GRAY_MID,  size = 11,
                                 margin = margin(b = 12)),
    plot.caption  = element_text(color = GRAY_MID,  size = 8,
                                 hjust = 0, margin = margin(t = 8)),

    # Legend
    legend.position    = "bottom",
    legend.title       = element_text(color = GRAY_DARK, size = 10,
                                      face = "bold"),
    legend.text        = element_text(color = GRAY_MID,  size = 9),
    legend.key.size    = unit(0.5, "lines"),
    legend.background  = element_rect(fill = "white", color = NA),

    # Facets
    strip.text       = element_text(color = GRAY_DARK, size = 10,
                                    face = "bold"),
    strip.background = element_rect(fill = GRAY_LIGHT, color = NA),

    # Margins
    plot.margin = margin(12, 16, 12, 12)
  )

# Set as default so scripts don't have to call it explicitly
theme_set(bills_theme)

# Discrete color palette (up to 3 groups: R / D / Divided)
# Kept restrained — black, navy, mid-gray — legible on white slides
TRIFECTA_COLORS <- c(
  "R"       = "#B0281A",   # muted red
  "D"       = ACCENT_COLOR, # navy
  "Divided" = "#6B6B6B"    # neutral gray
)

# ── Write global_constants.R (sourced by every downstream script) ────────────
writeLines(
  c(
    "# Auto-generated by 00_setup.R — do not edit by hand",
    paste0('SEED          <- ', SEED),
    paste0('MAX_BILLS     <- ', MAX_BILLS),
    paste0('RAW_DIR       <- "', RAW_DIR, '"'),
    paste0('ACCENT_COLOR  <- "', ACCENT_COLOR, '"'),
    paste0('GRAY_DARK     <- "', GRAY_DARK, '"'),
    paste0('GRAY_MID      <- "', GRAY_MID, '"'),
    paste0('GRAY_LIGHT    <- "', GRAY_LIGHT, '"'),
    'TRIFECTA_COLORS <- c(R = "#B0281A", D = "#2C4770", Divided = "#6B6B6B")',
    "",
    "# Shared ggplot2 theme — source this file, then theme_set(bills_theme)",
    "library(tidyverse)",
    "bills_theme <- theme_minimal(base_size = 13) +",
    "  theme(",
    "    plot.background  = element_rect(fill = 'white', color = NA),",
    "    panel.background = element_rect(fill = 'white', color = NA),",
    "    panel.grid.major.y = element_line(color = '#E8E8E8', linewidth = 0.4),",
    "    panel.grid.major.x = element_blank(),",
    "    panel.grid.minor   = element_blank(),",
    "    axis.text  = element_text(color = '#555555', size = 10),",
    "    axis.title = element_text(color = '#1A1A1A', size = 11, face = 'bold'),",
    "    axis.ticks = element_blank(),",
    "    axis.line  = element_blank(),",
    "    plot.title    = element_text(color = '#1A1A1A', size = 14, face = 'bold',",
    "                                 margin = margin(b = 6)),",
    "    plot.subtitle = element_text(color = '#555555', size = 11,",
    "                                 margin = margin(b = 12)),",
    "    plot.caption  = element_text(color = '#555555', size = 8,",
    "                                 hjust = 0, margin = margin(t = 8)),",
    "    legend.position    = 'bottom',",
    "    legend.title       = element_text(color = '#1A1A1A', size = 10, face = 'bold'),",
    "    legend.text        = element_text(color = '#555555', size = 9),",
    "    legend.key.size    = unit(0.5, 'lines'),",
    "    legend.background  = element_rect(fill = 'white', color = NA),",
    "    strip.text       = element_text(color = '#1A1A1A', size = 10, face = 'bold'),",
    "    strip.background = element_rect(fill = '#E8E8E8', color = NA),",
    "    plot.margin = margin(12, 16, 12, 12)",
    "  )",
    "theme_set(bills_theme)"
  ),
  con = "global_constants.R"
)

cat("\nglobal_constants.R written.\n")

# ── Checkpoint ───────────────────────────────────────────────────────────────
# CHECKPOINT: Verify expected outputs before moving on
cat("\n── Setup complete ──────────────────────────────────────────\n")
cat("PDFs ready:", length(pdf_files), "\n")
cat("Folders:   ", paste(dirs, collapse = ", "), "\n")
cat("Constants: global_constants.R\n")
cat("Proceed to 01_metadata.R — but CONFIRM LEGISCAN_KEY first.\n")

message("00_setup.R complete.")

# ── COMMON ERRORS AND FIXES ──────────────────────────────────────────────────
# ERROR: "cannot open zip file"
#   FIX:  Confirm ZIP_PATH is relative to your working directory.
#         Run setwd() or open the .Rproj before sourcing.
#
# ERROR: "No PDFs found"
#   FIX:  The zip may nest files differently. Check RAW_DIR with list.files().
#
# ERROR: "there is no package called 'tidyverse'"
#   FIX:  install.packages("tidyverse")
